# Generated by Django 5.2.13 on 2026-05-02 10:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('sphere', models.CharField(choices=[('FUNDAMENTALS_OF_PUBLIC_ADMINISTRATION', 'Davlat boshqaruvi asoslari'), ('CIVIL_LAW', 'Fuqarolik huquqi'), ('FAMILY', 'Oila'), ('LABOR_AND_EMPLOYMENT_OF_THE_POPULATION', 'Mehnat va aholi bandligi'), ('SOCIAL_SECURITY_SOCIAL_INSURANCE_AND_SOCIAL_PROTECTION', "Ijtimoiy ta'minot, sug'urta va himoya"), ('FINANCIAL_RELATIONS', 'Moliya munosabatlari'), ('BANKING_ACTIVITIES', 'Bank faoliyati'), ('HOUSEHOLD', 'Maishiy'), ('UTILITIES', 'Kommunal xizmatlar'), ('BUSINESS_ACTIVITIES', 'Tadbirkorlik'), ('HOUSEWIFELY_ACTIVITY', "Uy xo'jaligi"), ('ECONOMIC_ACTIVITY', 'Iqtisodiy faoliyat'), ('CUSTOMS_ACTIVITIES', 'Bojxona'), ('ECOLOGY_AND_ENVIRONMENT_PROTECTION', 'Ekologiya va atrof-muhitni muhofaza qilish'), ('SPHERE_OF_INFORMATION_TECHNOLOGY_AND_COMMUNICATIONS', 'AKT sohasi'), ('EDUCATION_SCIENCE', "Ta'lim, fan"), ('CULTURAL_WORKS', 'Madaniyat ishlari'), ('WORK_ON_PHYSICAL_CULTURE_AND_SPORTS', 'Jismoniy tarbiya va sport'), ('HEALTH_CARE_SECTOR', "Sog'liqni saqlash"), ('TOURIST_ACTIVITIES', 'Turizm'), ('ARMED_FORCES_DEFENSE', 'Qurolli kuchlar, mudofaa'), ('ENSURING_SECURITY_AND_LAW_AND_ORDER', 'Xavfsizlik va huquq tartibot'), ('JUDICIAL_BRANCH', 'Sud hokimiyati'), ('ACTIVITIES_OF_THE_PROSECUTORS_OFFICE', 'Prokuratura faoliyati'), ('JUSTICE_BODIES', 'Adliya organlari'), ('INTERNATIONAL_RELATIONS_INTERNATIONAL_LAW', 'Xalqaro munosabatlar, xalqaro huquq'), ('VARIOUS_QUESTIONS', 'Boshqa savollar')], max_length=128)),
                ('type', models.CharField(choices=[('Collection', "Yig'ilish"), ('Presidium', 'Prezidium'), ('Selector', 'Selektor'), ('Discussion', 'Muhokama'), ('Presentation', 'Taqdimot'), ('Meeting', 'Uchrashuv'), ('Forum', 'Forum'), ('Seminar', 'Seminar')], max_length=32)),
                ('is_important', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('conclusion', models.TextField(blank=True, default='')),
                ('notify_time', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='directions.direction')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_as_speaker', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_present', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, default='', max_length=1000)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_links', to='events.event')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events', through='events.EventParticipant', through_fields=('event', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PreEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('full_name', models.CharField(max_length=255)),
                ('organisation_name', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='events.event')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='events_even_date_5e8e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['speaker'], name='events_even_speaker_abae6a_idx'),
        ),
    ]
