# Generated by Django 5.2.13 on 2026-06-16 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0003_direction_head_direction_kind_direction_supervisor'),
        ('events', '0002_alter_event_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participant_directions',
            field=models.ManyToManyField(blank=True, related_name='events_as_target', to='directions.direction'),
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_speaker', to=settings.AUTH_USER_MODEL),
        ),
    ]
