# Generated by Django 5.2.13 on 2026-06-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_on_behalf_of'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreEvent',
        ),
    ]
