# Generated by Django 5.2.14 on 2026-06-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_delete_preevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['floor', 'name'],
            },
        ),
    ]
