# Generated by Django 5.2.14 on 2026-06-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_district_event_hall_event_region_hallbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sphere',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
