# Generated by Django 5.2.14 on 2026-06-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_sphere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sphere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Soha',
                'verbose_name_plural': 'Sohalar',
                'ordering': ['name'],
            },
        ),
    ]
