# Generated by Django 5.2.13 on 2026-05-05 09:00

import apps.drafts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directions', '0002_initial'),
        ('events', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Tahrir kutilmoqda'), ('PUBLISHED', 'Joylangan'), ('REJECTED', 'Rad etilgan'), ('EXPIRED', "Muddati o'tgan")], db_index=True, default='PENDING_REVIEW', max_length=32)),
                ('unresolved_participant_names', models.JSONField(blank=True, default=list, help_text='AI matnda topib olgan, lekin User jadvalida moslashmagan ismlar')),
                ('is_important', models.BooleanField(default=False)),
                ('notify_minutes_before', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('VOICE_TELEGRAM', 'Telegram ovozli xabar'), ('MANUAL', "Qo'lda kiritilgan")], default='MANUAL', max_length=32)),
                ('raw_transcript', models.TextField(blank=True, default='', help_text='STT chiqargan asl matn (audit uchun)')),
                ('parsed_json', models.JSONField(blank=True, default=dict, help_text='AI qaytargan asl JSON (debug uchun)')),
                ('voice_file', models.FileField(blank=True, help_text='Ovozli xabarning asl fayli', null=True, upload_to=apps.drafts.models._voice_upload_to)),
                ('voice_file_expires_at', models.DateTimeField(blank=True, default=apps.drafts.models._default_voice_expires_at, help_text="Ovoz fayl shu sanadan keyin Celery task tomonidan o'chiriladi", null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.CharField(blank=True, default='', max_length=500)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, help_text="Qoralamani tahrir qilib joylashi kerak bo'lgan xodim", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_draft', to='events.event')),
                ('suggested_participants', models.ManyToManyField(blank=True, help_text="AI taklif qilgan qatnashchilar (DB'dan topilgan)", related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_direction', models.ForeignKey(blank=True, help_text="Bo'lim aytilgan bo'lsa — bu yerda. assigned_to esa shu bo'lim HEAD'i", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directions.direction')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tadbir qoralamasi',
                'verbose_name_plural': 'Tadbir qoralamalari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'assigned_to'], name='drafts_even_status_679e36_idx'), models.Index(fields=['created_by', '-created_at'], name='drafts_even_created_c5553c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Tahrir kutilmoqda'), ('PUBLISHED', 'Joylangan'), ('REJECTED', 'Rad etilgan'), ('EXPIRED', "Muddati o'tgan")], db_index=True, default='PENDING_REVIEW', max_length=32)),
                ('unresolved_participant_names', models.JSONField(blank=True, default=list, help_text='AI matnda topib olgan, lekin User jadvalida moslashmagan ismlar')),
                ('is_important', models.BooleanField(default=False)),
                ('notify_minutes_before', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('VOICE_TELEGRAM', 'Telegram ovozli xabar'), ('MANUAL', "Qo'lda kiritilgan")], default='MANUAL', max_length=32)),
                ('raw_transcript', models.TextField(blank=True, default='', help_text='STT chiqargan asl matn (audit uchun)')),
                ('parsed_json', models.JSONField(blank=True, default=dict, help_text='AI qaytargan asl JSON (debug uchun)')),
                ('voice_file', models.FileField(blank=True, help_text='Ovozli xabarning asl fayli', null=True, upload_to=apps.drafts.models._voice_upload_to)),
                ('voice_file_expires_at', models.DateTimeField(blank=True, default=apps.drafts.models._default_voice_expires_at, help_text="Ovoz fayl shu sanadan keyin Celery task tomonidan o'chiriladi", null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.CharField(blank=True, default='', max_length=500)),
                ('deadline_text', models.CharField(blank=True, default='', help_text='"3 kun ichida" kabi so\'z bilan aytilgan muddat (description ichida ham bo\'lishi mumkin)', max_length=255)),
                ('assigned_to', models.ForeignKey(blank=True, help_text="Qoralamani tahrir qilib joylashi kerak bo'lgan xodim", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_draft', to='reports.report')),
                ('suggested_participants', models.ManyToManyField(blank=True, help_text="AI taklif qilgan qo'shma javobgar shaxslar", related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_direction', models.ForeignKey(blank=True, help_text="Bo'lim aytilgan bo'lsa — bu yerda. assigned_to esa shu bo'lim HEAD'i", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directions.direction')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topshiriq qoralamasi',
                'verbose_name_plural': 'Topshiriq qoralamalari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'assigned_to'], name='drafts_repo_status_764089_idx'), models.Index(fields=['created_by', '-created_at'], name='drafts_repo_created_15056c_idx')],
            },
        ),
    ]
