# Generated by Django 5.2.13 on 2026-05-05 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdraft',
            name='event_type',
            field=models.CharField(blank=True, default='', help_text='Joylashdan oldin tanlanishi kerak', max_length=32),
        ),
        migrations.AddField(
            model_name='eventdraft',
            name='speaker',
            field=models.ForeignKey(blank=True, help_text="Ma'ruzachi — joylashdan oldin tanlanadi (default: assigned_to)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventdraft',
            name='sphere',
            field=models.CharField(blank=True, default='', help_text='Joylashdan oldin tanlanishi kerak', max_length=128),
        ),
    ]
