# Generated by Django 5.2.14 on 2026-06-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0003_direction_head_direction_kind_direction_supervisor'),
        ('drafts', '0002_eventdraft_event_type_eventdraft_speaker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdraft',
            name='target_directions',
            field=models.ManyToManyField(blank=True, help_text="Tanlangan bo'lim/boshqarmalar — har birining boshlig'i qatnashchi bo'ladi", related_name='+', to='directions.direction'),
        ),
    ]
