# Generated by Django 5.2.13 on 2026-05-03 06:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('EVENT_REMINDER', 'Tadbir eslatmasi'), ('REPORT_FOLLOWUP', 'Hisobot eslatmasi')], max_length=32)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('notify_time', models.IntegerField(blank=True, null=True)),
                ('run_at', models.DateTimeField(db_index=True)),
                ('executed', models.BooleanField(db_index=True, default=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['run_at'],
                'indexes': [models.Index(fields=['executed', 'run_at'], name='scheduler_s_execute_43c61f_idx'), models.Index(fields=['event_id'], name='scheduler_s_event_i_063c5c_idx')],
            },
        ),
    ]
