# Generated by Django 5.2.13 on 2026-06-16 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_directions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direction',
            name='kind',
            field=models.CharField(choices=[('BOSHQARMA', 'Boshqarma'), ('BOLIM', "Bo'lim"), ('XIZMAT', 'Xizmat'), ('MUTAXASSIS', 'Yakka mutaxassis'), ('KOTIBIYAT', 'Kotibiyat'), ('BOSHQA', 'Boshqa')], default='BOLIM', max_length=16),
        ),
        migrations.AddField(
            model_name='direction',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_directions', to=settings.AUTH_USER_MODEL),
        ),
    ]
