# Generated by Django 5.2.13 on 2026-05-02 10:04

import apps.users.managers
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('directions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SUPER_ADMIN', 'Супер Админ'), ('PREMIER_MINISTER', 'Вазир'), ('VICE_MINISTER', 'Вазир ўринбосари'), ('ASSISTANT_PREMIER', 'Вазир ёрдамчиси'), ('HEAD', 'Бошлиқ'), ('ASSISTANT', 'Ёрдамчи'), ('ADMIN', 'Админ'), ('EMPLOYEE', 'Ходим')], max_length=32, unique=True)),
                ('label_uz', models.CharField(max_length=255)),
                ('label_ru', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(blank=True, default='', max_length=255)),
                ('position_uz', models.CharField(blank=True, default='', max_length=255)),
                ('position_ru', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('office_number', models.CharField(blank=True, default='', max_length=64)),
                ('company_car', models.JSONField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('AT_WORK', 'Ish joyida'), ('ON_HOLIDAY', "Ta'tilda"), ('WORK_TRIP', 'Komandirovkada'), ('DISMISSED', "Ishdan bo'shagan"), ('IN_CHILDHOOD_RAISING', 'Bola parvarishida')], default='AT_WORK', max_length=32)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='directions.direction')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.role')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
    ]
