# Generated by Django 5.2.13 on 2026-06-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super admin'), ('ADMIN', 'Admin'), ('VAZIR', 'Vazir'), ('ORINBOSAR', "Vazir o'rinbosari"), ('YORDAMCHI', 'Yordamchi'), ('BOSHLIQ', 'Boshliq'), ('XODIM', 'Xodim')], max_length=32, unique=True),
        ),
    ]
