# Generated by Django 5.2.13 on 2026-05-03 06:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('description', models.TextField()),
                ('reply', models.CharField(blank=True, choices=[('REJECTED', 'Rad etildi'), ('MUST_REJECT', 'Rad etilishi kerak'), ('BY_PHONE', 'Telefon orqali'), ('QUICKLY', 'Tezda'), ('EXECUTE', 'Bajarish kerak')], max_length=32, null=True)),
                ('reply_at', models.DateTimeField(blank=True, null=True)),
                ('notify_time', models.IntegerField(blank=True, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', '-created_at'], name='reports_rep_sender__8c6f68_idx'), models.Index(fields=['receiver', '-created_at'], name='reports_rep_receive_6542ce_idx'), models.Index(fields=['reply'], name='reports_rep_reply_0a4824_idx')],
            },
        ),
    ]
