# Generated by Django 5.2.13 on 2026-06-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='kind',
            field=models.CharField(choices=[('TASK', 'Topshiriq'), ('ANNOUNCEMENT', "E'lon"), ('REQUEST', "So'rov")], db_index=True, default='TASK', max_length=16),
        ),
    ]
