# Generated by Django 5.2.13 on 2026-06-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_initial'),
        ('reports', '0003_backfill_report_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='target_directions',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='directions.direction'),
        ),
    ]
