# Generated by Django 5.2.13 on 2026-06-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('EDITED', "O'zgartirildi"), ('DELETED', 'Bekor qilindi'), ('REMINDED', 'Eslatma'), ('PRE_EVENT', "Boshlang'ich tadbir"), ('ANNOUNCEMENT', "E'lon")], max_length=32),
        ),
    ]
