# Generated by Django 5.2.14 on 2026-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='report_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
